# Generated by Django 3.2.6 on 2024-01-21 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('user_id', models.CharField(blank=True, max_length=350, null=True)),
                ('access_token', models.CharField(blank=True, max_length=350, null=True)),
                ('password', models.CharField(blank=True, max_length=350, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_name', models.CharField(blank=True, max_length=350, null=True)),
                ('comments', models.IntegerField(blank=True, default=0, null=True)),
                ('likes', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_manager.instagram')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('followers', models.IntegerField(blank=True, default=0, null=True)),
                ('followings', models.IntegerField(blank=True, default=0, null=True)),
                ('media_count', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_manager.instagram')),
            ],
        ),
    ]
