# Generated by Django 3.2.6 on 2024-01-21 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram_manager', '0003_alter_instagram_main_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='main_user',
        ),
        migrations.AddField(
            model_name='instagram',
            name='main_user',
            field=models.ManyToManyField(related_name='instagram', to=settings.AUTH_USER_MODEL),
        ),
    ]
