# Generated by Django 3.2.6 on 2024-01-21 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram_manager', '0005_auto_20240121_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='main_user',
        ),
        migrations.AddField(
            model_name='instagram',
            name='main_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
