# Generated by Django 3.2.6 on 2024-01-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_profile_picture'),
        ('instagram_manager', '0006_auto_20240121_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='main_user',
        ),
        migrations.AddField(
            model_name='instagram',
            name='main_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
    ]
