# Generated by Django 3.2.6 on 2024-01-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_manager', '0007_auto_20240121_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_url',
            field=models.CharField(blank=True, max_length=1250, null=True),
        ),
    ]
