# Generated by Django 3.2.6 on 2024-01-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_manager', '0008_alter_account_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
