# Generated by Django 3.2.6 on 2024-01-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_manager', '0009_account_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_followers', models.CharField(blank=True, max_length=5000)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_manager.instagram')),
            ],
        ),
    ]
