# Generated by Django 3.2.6 on 2024-01-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_manager', '0010_topfollowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topfollowers',
            old_name='to_user',
            new_name='user_id',
        ),
    ]
