# Generated by Django 3.2.6 on 2024-01-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_manager', '0011_rename_to_user_topfollowers_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_caption',
            field=models.CharField(blank=True, max_length=625),
        ),
    ]
